module.exports = {
  CHAT: {
    NEW_MSG: 'NEW_MSG',
  },
  SOCKET: {
    CHAT_NEW_MSG: 'CHAT_NEW_MSG',
    PLAYER_JOINED: 'PLAYER_JOINED',
    PLAYER_LEFT: 'PLAYER_LEFT',
    PLAYER_REGISTER: 'PLAYER_REGISTER',
    PLAYER_REGISTERED: 'PLAYER_REGISTERED',
    PLAYER_ACTION: 'PLAYER_ACTION',
    START_GAME: 'START_GAME',
    PIECES: 'PIECES',
  },
  STATUS: {
    NOT_READY: 'NOT_READY',
    READY: 'READY',
    PLAYING: 'PLAYING',
  },
}
