export const CONSTANTS = {
  CHAT: {
    MESSAGE: 'CHAT_MESSAGE',
  },
  SOCKET: {
    REGISTER: 'REGISTER',
    LIST_USERS: 'LIST_USERS',
    PLAYER_JOINED: 'PLAYER_JOINED',
    PLAYER_LEFT: 'PLAYER_LEFT',
    PLAYER_REGISTERED: 'PLAYER_REGISTERED',
    PLAYER_ACTION: 'PLAYER_ACTION',
    START_GAME: 'START_GAME',
    PIECES: 'PIECES',
  },
  STATUS: {
    NOT_READY: 'NOT_READY',
    READY: 'READY',
    PLAYING: 'PLAYING',
  },
};
